main = ".open-next/worker.js"
name = "fileathome"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }
minify = true

# workers_dev = false
# route = { pattern = "planetanote.com/*", zone_name = "planetanote.com" }
# vars.BASE_URL = "https://fileathome.wcp1231.workers.dev"
# vars.AUTH_URL= "https://fileathome.wcp1231.workers.dev/api/auth"

[env.staging]
name = "fileathome-staging"
workers_dev = true

# vars.BASE_URL= "https://fileathome-staging.wcp1231.workers.dev"
# vars.AUTH_URL= "https://fileathome-staging.wcp1231.workers.dev/api/auth"
